name: addenvironment

on:
  push:
    branches: [ "environmentcreate" ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: false
    env:
        rootempfoldername: ${{ vars.rootempfoldername }}
    container: 
      image: kirankumarsivapuram/base_image:3.0             

    steps:
    - uses: actions/checkout@v3           
    - name: az login
      run: |
        az login --service-principal -u ${{secrets.user1}} -p ${{secrets.password1}} -t ${{secrets.azure_tenent_id}} 
        echo  ${{ vars.rootempfoldername }}
    
    - name: set subscription
      run: az account set --subscription ${{secrets.azure_subscription_id}}    
    - name: create container environment
      shell: pwsh
      run: |
        [int]$MinReplica = 0
        [int]$MaxReplica = 30
        $ContainerRegistry = "acrtestpoc"
        $RegistryPassword = "CSvdDR/VJRki0dWgukZ4r0TKVSx/lt+AxjZE7sDM22+ACRCxxwgp"
        az containerapp create -n conapppocjhijjm -g Container-app-rg --image acrtestpoc.azurecr.io/studente:one --environment container-app-env --ingress external --target-port 80 --registry-server acrtestpoc.azurecr.io --registry-username $ContainerRegistry --registry-password $RegistryPassword --query properties.configuration.ingress.fqdn --cpu 0.25 --memory 0.5Gi --min-replicas $MinReplica --max-replicas $MaxReplica --scale-rule-name azure-http-rule --scale-rule-type http --scale-rule-http-concurrency 20
