name: addcontainerregistry

on:
  push:
    branches: [ "main" ]   

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: false
   
    container: 
      image: kirankumarsivapuram/base_image:3.0           

    steps:
    - uses: actions/checkout@v3           
    - name: az login
      run: |

    - name: Terraform Init      
      run: terraform init       
        
    - name: Terraform Plan
      run: terraform plan -out="plan.tfplan" -var client_id="${{secrets.user1}}" -var client_secret="${{secrets.password1}}" 
    - name: Terraform Apply
      run: terraform apply -auto-approve "plan.tfplan"
