name: azcontenvwithprivatevnet

on:
  push:
    branches: [ "environmentcreate1" ]
  

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: false
    env:
        rootempfoldername: ${{ vars.rootempfoldername }}
    container: 
      image: kirankumarsivapuram/base_image:3.0             

    steps:
    - uses: actions/checkout@v3           
    - name: az login
      run: |
        az login --service-principal -u ${{secrets.user1}} -p ${{secrets.password1}} -t ${{secrets.azure_tenent_id}} 
        echo  ${{ vars.rootempfoldername }}
    
    - name: set subscription
      run: az account set --subscription ${{secrets.azure_subscription_id}}    
    - name: create container environment
      shell: pwsh
      run: |
        $CONTAINERAPPS_ENVIRONMENT= "${{ vars.containerappenvname }}"
        $RESOURCE_GROUP= "${{ vars.containerapprgname }}"
        $LOCATION= "${{ vars.containerappenvlocation }}"
        $workloadprofilename= "${{ vars.workloadprofilename }}"
        $WORKLOADPROFILETYPE= "${{ vars.WORKLOADPROFILETYPE }}"       
        $minnodes= "${{ vars.minnodes }}"
        $maxnodes= "${{ vars.maxnodes }}"
        $VNET_NAME = "${{ vars.VNETNAME }}"
        $Subnet_Name = "${{ vars.SUBNET_NAME }}"
        $vnetaddressprefix = "${{ vars.vnetaddressprefix }}"
        $subnetaddressprefix = "${{ vars.subnetaddressprefix }}"        
        write-output "app environment name is  : $CONTAINERAPPS_ENVIRONMENT"
        write-output "********** Creating resource group ***********"
        az group create --name $RESOURCE_GROUP --location $LOCATION
        write-output "********** Creating virtual netowork ***********"
        az network vnet create --resource-group $RESOURCE_GROUP --name $VNET_NAME --location $LOCATION --address-prefix $vnetaddressprefix
        write-output "********** Creating subnet for vnet ***********"
        az network vnet subnet create --resource-group $RESOURCE_GROUP --vnet-name $VNET_NAME --name $Subnet_Name --address-prefixes $subnetaddressprefix
        az network vnet subnet update --resource-group $RESOURCE_GROUP --name $Subnet_Name --vnet-name $VNET_NAME --delegations Microsoft.App/environments
        write-output "********** Retrieving subnet id***********"
        $subneid2=  $(az network vnet subnet list --resource-group $RESOURCE_GROUP --vnet-name $VNET_NAME --query "[?name=='$Subnet_Name'].id" --output tsv)
        echo $subneid2
        write-output "********** creating azure container app environement in specif vnet and subnet ***********"
        az containerapp env create --name $CONTAINERAPPS_ENVIRONMENT --resource-group $RESOURCE_GROUP --location "$LOCATION" --enable-workload-profiles --infrastructure-subnet-resource-id $subneid2
        az containerapp env workload-profile add -g $RESOURCE_GROUP -n $CONTAINERAPPS_ENVIRONMENT --workload-profile-name $workloadprofilename --workload-profile-type $WORKLOADPROFILETYPE --min-nodes $minnodes --max-nodes $maxnodes
        #az containerapp env create --name $CONTAINERAPPS_ENVIRONMENT --resource-group $RESOURCE_GROUP --location "$LOCATION" --enable-workload-profiles
        #az containerapp env workload-profile add -g $RESOURCE_GROUP -n $CONTAINERAPPS_ENVIRONMENT --workload-profile-name $workloadprofilename --workload-profile-type $Environmenttype --min-nodes $minnodes --max-nodes $maxnode    
        #az containerapp env workload-profile add -g $RESOURCE_GROUP -n $CONTAINERAPPS_ENVIRONMENT --workload-profile-name $workloadprofilename --workload-profile-type $WORKLOADPROFILETYPE --min-nodes $minnodes --max-nodes $maxnodes
